spring.application.name=WiproCircuitBreaker
# App config
server.port=8082

# Circuit breaker config
resilience4j.circuitbreaker.instances.deliveryService.register-health-indicator=true
resilience4j.circuitbreaker.instances.deliveryService.slidingWindowSize=5
resilience4j.circuitbreaker.instances.deliveryService.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.deliveryService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.deliveryService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.deliveryService.waitDurationInOpenState=5s
